export type RepositoryRecord = {
  fullName: string;
  category: string;
  description: string;
  technologies: string[];
  tags: string[];
  useCases: string[];
  highlights: string[];
  repoUrl: string;
};

export const repositoryCatalog: RepositoryRecord[] = [
  {
    fullName: 'vuejs/core',
    category: 'frontend',
    description: 'Vue 3 核心仓库，适合构建组件化前端应用。',
    technologies: ['vue', 'typescript', 'javascript'],
    tags: ['frontend', 'ui', '响应式', '组件'],
    useCases: ['前端框架', '中后台', '组件化开发'],
    highlights: ['Vue 生态核心', '响应式系统成熟', '适合做框架能力参考'],
    repoUrl: 'https://github.com/vuejs/core',
  },
  {
    fullName: 'vercel/next.js',
    category: 'frontend',
    description: 'React 全栈框架，覆盖 SSR、RSC、路由和部署一体化。',
    technologies: ['react', 'next.js', 'typescript', 'node.js'],
    tags: ['frontend', 'fullstack', 'ssr', 'react'],
    useCases: ['官网', '内容站点', '全栈 web 应用'],
    highlights: ['SSR 和 RSC 能力强', '生态成熟', '适合现代 React 架构参考'],
    repoUrl: 'https://github.com/vercel/next.js',
  },
  {
    fullName: 'nestjs/nest',
    category: 'backend',
    description: '面向企业级 Node.js 服务端开发的模块化框架。',
    technologies: ['node.js', 'typescript', 'nestjs'],
    tags: ['backend', 'api', '架构', '模块化'],
    useCases: ['BFF', '微服务', '企业后台'],
    highlights: ['分层清晰', '适合中大型后端架构', '工程化能力完整'],
    repoUrl: 'https://github.com/nestjs/nest',
  },
  {
    fullName: 'fastify/fastify',
    category: 'backend',
    description: '高性能 Node.js Web 框架，适合轻量 API 和高吞吐场景。',
    technologies: ['node.js', 'javascript', 'typescript', 'fastify'],
    tags: ['backend', 'api', 'performance', 'server'],
    useCases: ['轻量服务', '网关', '高性能接口'],
    highlights: ['性能优秀', '插件机制清晰', '适合性能导向项目'],
    repoUrl: 'https://github.com/fastify/fastify',
  },
  {
    fullName: 'langchain-ai/langchainjs',
    category: 'ai',
    description: 'Node.js 生态下常用的 LLM 应用编排框架。',
    technologies: ['node.js', 'typescript', 'langchain'],
    tags: ['ai', 'llm', 'agent', 'rag'],
    useCases: ['AI Agent', 'RAG', '工作流编排'],
    highlights: ['大模型应用生态完整', '适合快速验证 Agent 能力', '集成多模型与向量库'],
    repoUrl: 'https://github.com/langchain-ai/langchainjs',
  },
  {
    fullName: 'modelcontextprotocol/servers',
    category: 'ai',
    description: 'MCP 官方 server 示例集合，适合构建工具调用型 Agent。',
    technologies: ['typescript', 'node.js', 'mcp'],
    tags: ['ai', 'agent', 'tool-use', 'mcp'],
    useCases: ['工具接入', 'Agent 外挂能力', 'MCP server 参考'],
    highlights: ['MCP 协议实践样例丰富', '适合做工具扩展层架构参考', '对接外部系统方便'],
    repoUrl: 'https://github.com/modelcontextprotocol/servers',
  },
  {
    fullName: 'n8n-io/n8n',
    category: 'automation',
    description: '开源工作流自动化平台，擅长连接 API、数据库和第三方服务。',
    technologies: ['node.js', 'typescript', 'vue'],
    tags: ['automation', 'workflow', 'low-code', 'integration'],
    useCases: ['流程编排', '自动化任务', '系统集成'],
    highlights: ['节点生态丰富', '低代码编排体验好', '适合自动化平台场景'],
    repoUrl: 'https://github.com/n8n-io/n8n',
  },
  {
    fullName: 'supabase/supabase',
    category: 'database',
    description: '开源 Firebase 替代方案，整合数据库、认证、存储和实时能力。',
    technologies: ['typescript', 'postgres', 'react'],
    tags: ['database', 'backend', 'auth', 'realtime'],
    useCases: ['快速搭建后端', '用户系统', '实时数据应用'],
    highlights: ['后端基础设施一站式', '认证和数据库结合紧密', '适合快速产品验证'],
    repoUrl: 'https://github.com/supabase/supabase',
  },
  {
    fullName: 'payloadcms/payload',
    category: 'backend',
    description: '基于 TypeScript 的现代 Headless CMS，适合内容驱动型产品。',
    technologies: ['typescript', 'node.js', 'react'],
    tags: ['backend', 'cms', 'content', 'fullstack'],
    useCases: ['内容管理', '运营后台', 'Headless CMS'],
    highlights: ['TypeScript 体验好', '管理后台可扩展', '适合内容平台项目'],
    repoUrl: 'https://github.com/payloadcms/payload',
  },
  {
    fullName: 'open-webui/open-webui',
    category: 'ai',
    description: '面向大模型交互和团队使用场景的开源 Web UI。',
    technologies: ['typescript', 'python', 'docker'],
    tags: ['ai', 'llm', 'chat', 'workspace'],
    useCases: ['模型交互界面', '团队 AI 门户', '多模型接入'],
    highlights: ['适合做 AI 门户产品参考', '多模型兼容', '界面成型快'],
    repoUrl: 'https://github.com/open-webui/open-webui',
  },
  {
    fullName: 'remotion-dev/remotion',
    category: 'media',
    description: '基于 React 的视频生成与渲染框架，适合做 Web 视频生产和模板化渲染。',
    technologies: ['react', 'typescript', 'web', 'remotion'],
    tags: ['media', 'video', 'render', 'timeline', 'web'],
    useCases: ['Web 视频生成', '模板渲染', '云剪辑渲染层'],
    highlights: ['适合做云剪辑渲染架构参考', 'React 生态接入顺滑', '视频生产链路成熟'],
    repoUrl: 'https://github.com/remotion-dev/remotion',
  },
  {
    fullName: 'ffmpegwasm/ffmpeg.wasm',
    category: 'media',
    description: '将 FFmpeg 运行在浏览器中的方案，适合前端剪辑导出和转码场景。',
    technologies: ['typescript', 'web', 'ffmpeg'],
    tags: ['media', 'video', 'transcode', 'export', 'wasm'],
    useCases: ['浏览器转码', '视频导出', '云剪辑导出能力'],
    highlights: ['适合做前端导出与转码架构参考', '浏览器侧媒体处理能力强', '可补齐云剪辑导出链路'],
    repoUrl: 'https://github.com/ffmpegwasm/ffmpeg.wasm',
  },
  {
    fullName: 'xzdarcy/react-timeline-editor',
    category: 'media',
    description: 'React 时间线编辑器组件，适合做多轨道剪辑和时间轴交互参考。',
    technologies: ['react', 'typescript', 'web'],
    tags: ['media', 'timeline', 'editor', 'web', 'ui'],
    useCases: ['时间线编辑器', '多轨道剪辑', '云剪辑前端'],
    highlights: ['适合做云剪辑时间线交互参考', '多轨道编辑能力清晰', '前端编辑器实现路径直接'],
    repoUrl: 'https://github.com/xzdarcy/react-timeline-editor',
  },
  {
    fullName: 'konvajs/konva',
    category: 'media',
    description: 'Canvas 2D 图形框架，适合做素材画布、字幕层和可视编辑器。',
    technologies: ['javascript', 'typescript', 'canvas', 'konva'],
    tags: ['media', 'canvas', 'editor', 'timeline', 'web'],
    useCases: ['可视化编辑器', '字幕与贴纸编排', '素材画布层'],
    highlights: ['适合做画布编辑层架构参考', '交互能力成熟', '适合视频编辑器前端画布层'],
    repoUrl: 'https://github.com/konvajs/konva',
  },
];
